version: '3.1'

services:
  db:
    image: ${POSTGRES_TAG}
    restart: always
    ports:
        - ${POSTGRES_PORT}:5432
    volumes: 
       - PGDATA:/var/lib/postgresql/data
    networks: 
        webnet:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    
  adminer:
    image: ${ADMINER_TAG}
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks: 
       webnet:
  app:
    image: ${NODE_TAG}
    restart: always
    working_dir: /home/src
    command: npm start:debug
    depends_on: 
        - db
    ports: 
        - ${APP_PORT}:${APP_PORT}
    volumes: 
        - .:/home/dist
    networks: 
        webnet:
networks: 
    webnet:
volumes: 
     PGDATA: